spring:
  datasource:
    username: root
    password: ****
    url: jdbc:mysql://47.103.29.1:3306/standardtest
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: standardservicecloud-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
